version: '3'

services:
  web:
    build:
      context: ./web
      dockerfile: .Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 app:app
    expose:
      - 5000

  nginx:
    build:
      context: ./nginx
      dockerfile: .Dockerfile
    ports:
      - 1337:80
    depends_on:
      - web